In [1]:
import pandas as pd

In [3]:
pd.read_csv("six_nations_stats2.csv")

,Assists,Attacking scrum win,Average points,Breakdown steal,Club,Conceded penalty,Conversion,Defenders beaten,Drop goal,ID,...,Metres carried,Name,Offloads,Penalty,Position,Position Name,Red cards,Tackles,Try,Yellow cards
0,NaN,7.0,31.0,NaN,France,NaN,NaN,3.0,NaN,244767,...,17.0,O. Jegou,1.0,NaN,10,Back Row,NaN,15.0,NaN,NaN
1,NaN,7.0,30.0,NaN,France,NaN,NaN,1.0,NaN,175065,...,5.0,A. Jelonch,2.0,NaN,10,Back Row,NaN,17.0,NaN,NaN
2,NaN,6.0,44.0,1.0,Italy,1.0,NaN,4.0,NaN,197335,...,50.0,L. Cannone,1.0,NaN,10,Back Row,NaN,19.0,NaN,NaN
3,NaN,6.0,31.0,NaN,Italy,1.0,NaN,NaN,NaN,208272,...,4.0,N. Cannone,NaN,NaN,11,Second Row,NaN,26.0,NaN,NaN
4,NaN,5.0,50.0,NaN,England,1.0,NaN,3.0,NaN,209612,...,69.0,B. Earl,1.0,NaN,10,Back Row,NaN,17.0,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224,NaN,NaN,NaN,NaN,Ireland,NaN,NaN,NaN,NaN,254559,...,NaN,B. Bohan,NaN,NaN,12,Prop,NaN,NaN,NaN,NaN
225,NaN,NaN,NaN,NaN,Scotland,NaN,NaN,NaN,NaN,172959,...,NaN,D. Rae,NaN,NaN,12,Prop,NaN,NaN,NaN,NaN
226,NaN,NaN,NaN,NaN,Scotland,NaN,NaN,NaN,NaN,207013,...,NaN,A. Craig,NaN,NaN,11,Second Row,NaN,NaN,NaN,NaN
227,NaN,NaN,NaN,NaN,Wales,NaN,NaN,NaN,NaN,196875,...,NaN,F. Thomas,NaN,NaN,11,Second Row,NaN,NaN,NaN,NaN
228,NaN,NaN,NaN,NaN,Wales,NaN,NaN,NaN,NaN,167563,...,NaN,S. Wainwright,NaN,NaN,12,Prop,NaN,NaN,NaN,NaN

In [2]:
_df = pd.read_csv("six_nations_stats.csv")

In [5]:
_df.head()

,Assists,Attacking scrum win,Breakdown steal,Club,Conceded penalty,Conversion,Defenders beaten,Drop goal,ID,Kick 50-22,...,Offloads,Penalty,Position,Position Name,Pts,Red cards,Tackles,Try,Yellow cards,gameweek
0,NaN,7.0,NaN,France,NaN,NaN,3.0,NaN,244767,NaN,...,1.0,NaN,10,Back Row,31.0,NaN,15.0,NaN,NaN,1
1,NaN,7.0,NaN,France,NaN,NaN,1.0,NaN,175065,NaN,...,2.0,NaN,10,Back Row,30.0,NaN,17.0,NaN,NaN,1
2,NaN,6.0,1.0,Italy,1.0,NaN,4.0,NaN,197335,NaN,...,1.0,NaN,10,Back Row,44.0,NaN,19.0,NaN,NaN,1
3,NaN,6.0,NaN,Italy,1.0,NaN,NaN,NaN,208272,NaN,...,NaN,NaN,11,Second Row,31.0,NaN,26.0,NaN,NaN,1
4,NaN,5.0,NaN,England,1.0,NaN,3.0,NaN,209612,NaN,...,1.0,NaN,10,Back Row,50.0,NaN,17.0,1.0,NaN,1